$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)
require "factory_girl"
require "support/factory_girl"
require "pry"
require_relative "../lib/command"
require_relative "../lib/robot"
require_relative "../lib/arena"
require_relative "../lib/null_arena"
require_relative "../lib/position"
require_relative "../lib/real_position"
require_relative "../lib/null_position"
